name: Daily Data Update
on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8点
  workflow_dispatch:      # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jinja2

      - name: Run data update
        run: |
          cd scripts
          python update_data.py
          
      - name: Commit changes
        run: |
          git config --global user.name "Automated Updater"
          git config --global user.email "actions@github.com"
          git add ../index.html
          git commit -m "Auto: Daily data update"
          git push